// Barrel export for shared 3D objects
// Import from '@/components/scene/spaces/objects' in space components

export { ArtObject } from './ArtObject'
export { ArtObjects } from './ArtObjects'
export { Ceiling } from './Ceiling'
export { CeilingGlass } from './CeilingGlass'
export { CeilingLight } from './CeilingLight'
export { Display } from './Display'
export { Door } from './Door'
export { Floor } from './Floor'
export { Frame } from './Frame'
export { Lamp } from './Lamp'
export { Line } from './Line'
export { Passepartout } from './Passepartout'
export { ParisWindow } from './ParisWindow'
export { Placeholder } from './Placeholder'
export { Radiator } from './Radiator'
export { RectLamp } from './RectLamp'
export { RectLight } from './RectLight'
export { Reel } from './Reel'
export { Sockets } from './Sockets'
export { Stencil } from './Stencil'
export { Support } from './Support'
export { Wall } from './Wall'
export { Window } from './Window'

