// Barrel export for shared 3D objects
// Import from '@/components/scene/spaces/objects' in space components

export { ArtObject } from './ArtObject'
export { ArtObjects } from './ArtObjects'
export { Ceiling } from './Ceiling'
export { Display } from './Display'
export { Door } from './Door'
export { Floor } from './Floor'
export { Frame } from './Frame'
export { Passepartout } from './Passepartout'
export { ParisWindow } from './ParisWindow'
export { Placeholder } from './Placeholder'
export { Radiator } from './Radiator'
export { RecessedLamp } from './RecessedLamp'
export { SingleSocket } from './SingleSocket'
export { Stencil } from './Stencil'
export { Support } from './Support'
export { Switch } from './Switch'
export { TrackLamp } from './TrackLamp'
export { Wall } from './Wall'
