import type { TWallView } from '@/types/wallView'

export const wallViewFactory = (): TWallView => ({
  isWallView: false,
  currentArtworkId: null,
  currentWallId: null,
  editingArtworkId: null,
  currentWallCoordinates: { x: 0, y: 0, z: 0 },
  currentWallNormal: { x: 0, y: 0, z: 1 },
  scaleFactor: 0.30,
  panPosition: { x: -50, y: -50 },
  isHumanVisible: false,
  wallHeight: null,
  wallWidth: null,
  isDragging: false,
  isDraggingGroup: false,
  isResizing: false,
  isShiftKeyDown: false,
  sizeLockedById: {},
  artworkGroupIds: [],
  artworkGroup: {
    groupY: 0,
    groupX: 0,
    groupHeight: 0,
    groupWidth: 0,
  },
  isGroupHovered: false,
  alignedPairs: [],
  isGridVisible: false,
  snapEnabledById: {},
})
